package ru.nikpanfilov.delivery.core.ui.theme

import androidx.compose.ui.graphics.Color

val DarkPrimary = Color(0xFF4FA6DC)
val DarkOnPrimary = Color(0xFFFFFFFF)
val DarkInversePrimary = Color(0xFFEC1D44)
val DarkSecondary = Color(0xFF616161)
val DarkOnSecondary = Color(0xFFBDBDBD)
val DarkSurface = Color(0xFF2B2B2B)
val DarkOnSurface = Color(0xFFE8E8E8)
val DarkOnSurfaceVariant = Color(0xFF9C9C9C)
val DarkSurfaceContainer = Color(0xFF5A5A5A)
val DarkOnSurfaceContainer = Color(0xFF9C9C9C)
val DarkBackground = Color(0xFF212121)
val DarkOnBackground = Color(0xFFF5F5F5)
val DarkOutline = Color(0xFF616161)
val DarkRipple = Color(0xFF90CCF1)
val DarkOnRipple = Color(0xFFFFFFFF)
val DarkError = Color(0xFFEF5350)
val DarkOnError = Color(0xFFFFFFFF)
val DarkOnTertiary = Color(0xFFF5F5F5)
val DarkSurfaceDim = Color(0xFF464646)
val DarkInverseOnSurface = Color(0xFF74C3FD)

val Primary = Color(0xFF4FA6DC)
val OnPrimary = Color(0xFFFFFFFF)
val InversePrimary = Color(0xFFEC1D44)
val Secondary = Color(0xFFBDBDBD)
val OnSecondary = Color(0xFFFFFFFF)
val Surface = Color(0xFFFFFFFF)
val OnSurface = Color(0xFF212121)
val OnSurfaceVariant = Color(0xFF757575)
val SurfaceContainer = Color(0xFF79747E)
val OnSurfaceContainer = Color(0xFF757575)
val Background = Color(0xFFFDFDFD)
val OnBackground = Color(0xFF212121)
val Ripple = Color(0xFF90CCF1)
val OnRipple = Color(0xFFFFFFFF)
val Error = Color(0xFFDC362E)
val OnError = Color(0xFFFFFFFF)
val Outline = Color(0xFF79747E)
val OutlineVariant = Color(0xFFDDDDDD)
val OnTertiary = Color(0xFFF5F5F5)
val surfaceDim = Color(0xFFE6E6E6)
val inverseOnSurface = Color(0xFF077DD3)